### ISSUE TITLE
Add more distributions

### ISSUE THREAD

**Issue by DenisKolodin** [stainless-steel/probability#11]
@IvanUkhov Your library is great! Good test coverage. I like it :+1: 
What about to add more features? I can help with PRs.

I've found a distributions list [there](https://www.palisade.com/downloads/manuals/EN/RISK5_EN.pdf). 
- [x] Bernoulli
- [x] Beta
- [x] Binomial
- [x] Categorical
- [x] Exponential
- [x] Gamma
- [x] Gaussian
- [x] Logistic
- [x] Lognormal
- [x] Triangular
- [x] Uniform
- [ ] Chi-Square
- [ ] Poisson
- [ ] Erlang
- [ ] Student’s t
- [ ] Weibull
- [ ] Geometric
- [ ] Pareto
- [ ] Hypergeometric
- [ ] Extreme Value
- [ ] Negative Binomial
- [ ] Cumulative
- [ ] Error Function
- [ ] General
- [ ] Histogram
- [ ] Inverse Gaussian
- [ ] IntUniform
- [ ] Log-Logistic
- [ ] Lognormal2
- [ ] Pareto2
- [ ] Pearson V
- [ ] Pearson VI
- [ ] PERT
- [ ] Rayleigh
- [ ] Beta-Subjective
- [ ] Trigen

What do you think about this list?

I already have implementations of some with C and want to move it to Rust and found your library is the best place to do it. What about to implement most of them?

**Comment by IvanUkhov** [comment]
Thank you for the issue! It definitely would be great to have as broad coverage of distributions as possible. I usually implement only what I use myself. In this way, I’m more confident in what I write and can test the corresponding code more intelligently. That’s why the library grows only when I need some particular distribution, or when someone is willing to contribute.

The bottom line is: you’re very welcome to contribute if you have time. I think it makes sense to prioritize those distributions that are the most common and widely used. Thank you!

**Comment by DenisKolodin** [comment]
Awesome! As first step I'll add `Trianguar`, `Lognormal` and `Logistic` distributions and send you different PRs to check. These three are essential for simulation modeling.

Let's keep this issue opened as **TODO** list and mark implemented distributions here.

**Comment by IvanUkhov** [comment]
Sounds great! I just want to note that, since there are different traits covering different aspects of a probability distribution, one doesn’t necessarily have to implement them all in order to get a working version of the distribution. Some things might be too difficult to implement or might not have efficient implementations. In such cases, it’s better to just skip that functionality all together. To give a concrete example, `Gamma` doesn’t implement `Median` as there is “[no simple closed form](https://en.wikipedia.org/wiki/Gamma_distribution).”

**Comment by DenisKolodin** [comment]
Ok, traits system are well-designed here. I'll obey perfomance and mathematical reasons.

**Comment by DenisKolodin** [comment]
Three next three I'll take to pieces: `ChiSquare`, `Poisson` and `Erlang`. I'll also explore `Gamma` to reuse it, because they have some intersections.

**Comment by leodasvacas** [comment]
The [half-normal](https://en.wikipedia.org/wiki/Half-normal_distribution) would be useful for me. It can be easily derived from the normal, but the traits would be different.
