### ISSUE TITLE
Laplace Distribution

### ISSUE THREAD

**Issue by knappador** [stainless-steel/probability#22]
Wikipedia's definition looks pretty straightforward.  I started work by copying the exponential.rs and just replacing formulas.

What's the scope of work that needs to be done on all new distributions?

**Comment by IvanUkhov** [comment]
Thanks for the issue! Well, it just has to follow the established conventions and be covered by unit tests. Regarding the functionality, one can implement as many of the distribution-related traits as one has time for; the rest could be contributed by somebody else later on.
