### ISSUE TITLE
Case in which Newton method for Binomial::inverse does not converge

### ISSUE THREAD

**Issue by msoeken** [stainless-steel/probability#28]
The following test results in an infinite loop in version 0.18 due to the Newton method not converging.

```rust
#[test]
fn inverse_non_converging() {
    let p = 0.9810204628647335;
    let n = 3666;
    let q = 0.0033333333333332993;

    let dist = Binomial::new(n, p);
    let k = dist.inverse(q);

    println!("k = {k}");
}
```

**Comment by IvanUkhov** [comment]
Thank you for the report! Would be nice to find out how other packages handle this.

**Comment by IvanUkhov** [comment]
I reopen this, as the new implementation is very inefficient for large `n`.

**Comment by IvanUkhov** [comment]
Here is an alternative implementation:

https://github.com/SurajGupta/r-source/blob/master/src/nmath/qbinom.c

**Comment by IvanUkhov** [comment]
Seem like the Newton method was not converging because of the discretization inside. The example you provided works with the new version. But hard to give guarantees that there are no more such cases.

**Comment by nothingelsematters** [comment]
> But not sure about guarantees that there are no more such cases.

Apparently, I've stumbled upon one of them:

```rust
#[test]
fn inverse_non_converging() {
    let n = 1024;
    let p = 0.009765625;
    let q = 0.32185663510619567;

    let dist = Binomial::new(n, p);
    let k = dist.inverse(q);

    println!("k = {k}");
}
```

There are a lot of examples with the same `n` and `p`: I use random `q`s and quite often it hangs up.

**Comment by IvanUkhov** [comment]
Interesting. Thank you! One should continue thinking further. If it is some oscillating behavior, it should be easy to catch it and terminate.

**Comment by IvanUkhov** [comment]
Made yet another attempt. This time added a decay factor to ensure it terminates eventually. See #32.
