### ISSUE TITLE
RFC: Make parameters private

### ISSUE THREAD

**Issue by IvanUkhov** [stainless-steel/probability#8]
Should the parameters of a distribution be private?

Pros:

1. The internal state of a distribution is protected.

Cons:

1. One has to provide getters.
2. One has to type two additional characters, that is, `()`, to access a parameter.
3. Once created, a distribution cannot change (unless setters are provided as well).

**Comment by runarberg** [comment]
:+1 The benefits of protecting the internal state by far outweigh the the few extra characters needed in the source.

One needs setters anyway in most distributions to update precomputed values, else the methods will most likely deliver wrong results.
